Support getPreviewer()
Shougo/ddu-kind-file pull request #3
Opened 2022-05-03 08:02 UTC by matsui54

I will fix the import path and add doc if Shougo/ddu.vim#16 is marged.

2022-05-04 01:56 UTC, Shougo commented on denops/@ddu-kinds/file.ts
> +} from "../../../ddu.vim/denops/ddu/types.ts";
Why it uses relative path?   It should not.

2022-05-04 01:56 UTC, Shougo commented on denops/@ddu-kinds/file.ts
> +} from "../../../ddu.vim/denops/ddu/deps.ts";
Why it uses relative path? It should not.

2022-05-04 01:57 UTC, Shougo requested changes
Please fix my commented code.

2022-05-04 02:03 UTC, Shougo commented
The documentation update is needed for `PreviewOption`.

2022-05-04 03:31 UTC, matsui54 commented
Fixed the problems.

2022-05-04 03:48 UTC, merged

2022-05-07 06:52 UTC, Shougo commented
I have merged it.  But `useBat` should specify preview command instead.

2022-05-08 04:09 UTC, matsui54 commented
Fixed. https://github.com/Shougo/ddu-kind-file/pull/4